name: RSS Processing Workflow

on:
  schedule:
    - cron: '0 * * * *'        # 每小时的 0 分钟执行 process_rss_feeds.py
    - cron: '10 17 * * *'     # 每天下午 5 点 10 分 (17:10) 执行 rss_aggregator.py

jobs:
  rss_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 或者指定 Python 版本

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run process_rss_feeds.py
        if: github.event.schedule == '0 * * * *'
        run: python process_rss_feeds.py #只需要运行这个文件

      - name: Run rss_aggregator.py 
        if: github.event.schedule == '10 17 * * *' #每天下午 5 点 10 分 (17:10) 执行
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}  # 使用 GitHub Secrets
          YOUR_SITE_URL: ${{ secrets.YOUR_SITE_URL }}
          YOUR_SITE_NAME: ${{ secrets.YOUR_SITE_NAME }}
        run: python rss_aggregator.py #只需要运行这个文件
          
